# Generated by Django 5.1.3 on 2024-11-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='dateEmprunt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='disponible',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='emprunteur',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
