# Generated by Django 5.1.3 on 2024-11-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0002_items_dateemprunt_items_disponible_items_emprunteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeudeplateau',
            name='createur',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
