# Generated by Django 5.1.3 on 2024-12-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0006_alter_items_dateemprunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunteur',
            name='EmpruntPossible',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
